name: KeywordHanaro FE CI/CD
on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup node pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: setup pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        working-directory: .
        run: pnpm install

      - name: set .env
        working-directory: .
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build with Next.js
        working-directory: .
        run: pnpm next build

      - name: zip next
        working-directory: .
        run: zip -rq next.zip .next

      - name: scp next to was
        run: |
          scp KeywordHanaro_FE/next.zip ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/

      - name: restart next
        run: |
          ssh ec2-user@${{ secrets.WAS }} '
            cd /home/ec2-user/workspace &&
            rm -rf KeywordHanaro_FE/.next
            unzip next.zip -d KeywordHanaro_FE &&
            pm2 reload keyword-next
          '
